import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";

const roboto_init = Roboto({
  subsets: ['latin'],
  weight: '500',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  variable: '--font-roboto',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto_init.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
